// ─── Curriculum Data ──────────────────────────────────────────────────────────
// Edit this file to add, reorder, or update paths and blocks.
// Statuses (locked/unlocked/complete) are derived at runtime from user progress.

export interface BlockDef {
  id: string;
  order: number;
  title: string;
  subtitle: string;
  description: string;
  skills: string[];
  lessonCount: number;
  problemCount: number;
}

export interface PathDef {
  id: string;
  order: number;          // 1-indexed, determines unlock sequence
  title: string;
  description: string;
  blocks: BlockDef[];
}

export const CURRICULUM: PathDef[] = [
  // ── PATH 1 ──────────────────────────────────────────────────────────────────
  {
    id: 'python-foundations',
    order: 1,
    title: 'Python Foundations',
    description: 'Learn enough Python to comfortably write and read solution code.',
    blocks: [
      {
        id: 'p1-variables',
        order: 1,
        title: 'Variables and Basic Types',
        subtitle: 'ints, floats, strings, booleans',
        description: 'Understand the core data types Python uses. Every coding problem starts here.',
        skills: ['Variable assignment', 'Integers & floats', 'Strings', 'Booleans', 'print()', 'I/O mindset'],
        lessonCount: 5,
        problemCount: 3,
      },
      {
        id: 'p1-operators',
        order: 2,
        title: 'Operators and Expressions',
        subtitle: 'arithmetic, comparison, logical operators',
        description: 'Learn to compute values, compare them, and combine conditions — the core of every problem.',
        skills: ['Arithmetic operators', 'Comparison operators', 'Logical (and / or / not)', 'Assignment shortcuts', 'Expression evaluation'],
        lessonCount: 4,
        problemCount: 4,
      },
      {
        id: 'p1-conditionals',
        order: 3,
        title: 'Conditionals',
        subtitle: 'if, elif, else, decision logic',
        description: 'Write programs that branch based on conditions. Nearly every problem requires this.',
        skills: ['if / elif / else', 'Nested conditionals', 'Boolean conditions', 'Simple decision logic'],
        lessonCount: 4,
        problemCount: 5,
      },
      {
        id: 'p1-loops',
        order: 4,
        title: 'Loops',
        subtitle: 'for, while, range, enumerate, break/continue',
        description: 'Iterate over data and repeat operations. Loops are the backbone of most solutions.',
        skills: ['for loops', 'while loops', 'range()', 'enumerate()', 'break & continue', 'Nested loops'],
        lessonCount: 5,
        problemCount: 6,
      },
      {
        id: 'p1-functions',
        order: 5,
        title: 'Functions',
        subtitle: 'defining, parameters, return values, scope',
        description: 'Organize code into reusable pieces. LeetCode solutions are always written as functions.',
        skills: ['def keyword', 'Parameters & arguments', 'return values', 'Scope basics', 'Helper functions', 'class Solution pattern'],
        lessonCount: 5,
        problemCount: 5,
      },
      {
        id: 'p1-lists',
        order: 6,
        title: 'Lists and Strings',
        subtitle: 'indexing, slicing, traversal, methods',
        description: "Master Python's most-used data structure. Lists appear in 80% of LeetCode problems.",
        skills: ['List creation', 'Indexing & slicing', 'Iteration', 'append / pop', 'len()', 'String traversal', 'String methods'],
        lessonCount: 6,
        problemCount: 8,
      },
      {
        id: 'p1-dicts',
        order: 7,
        title: 'Dictionaries and Sets',
        subtitle: 'key-value lookup, frequency counting',
        description: 'These two structures unlock O(n) solutions. Dicts alone cover dozens of patterns.',
        skills: ['Dict creation & lookup', 'Updating values', 'Iterating dicts', 'Frequency counting', 'Set membership', 'Duplicate detection'],
        lessonCount: 5,
        problemCount: 7,
      },
      {
        id: 'p1-solve',
        order: 8,
        title: 'Python Problem Solving Basics',
        subtitle: 'reading problems, tracing, warmup practice',
        description: 'Put it all together. Read a problem, trace through code, and write your first solutions.',
        skills: ['Reading problem statements', 'Tracing variables', 'Writing simple functions', 'Edge case thinking', 'Warmup practice'],
        lessonCount: 4,
        problemCount: 10,
      },
    ],
  },

  // ── PATH 2 ──────────────────────────────────────────────────────────────────
  {
    id: 'core-data-structures',
    order: 2,
    title: 'Core Data Structures',
    description: 'Learn the building blocks that appear in almost every coding interview.',
    blocks: [
      {
        id: 'p2-arrays',
        order: 1,
        title: 'Arrays and Strings',
        subtitle: 'traversal, indexing, prefix ideas, manipulation',
        description: 'The most common interview structure. Get fully comfortable working with sequences.',
        skills: ['Array traversal', 'Two-index access', 'Prefix ideas', 'Counting elements', 'String manipulation'],
        lessonCount: 5,
        problemCount: 8,
      },
      {
        id: 'p2-hashmaps',
        order: 2,
        title: 'Hash Maps',
        subtitle: 'O(1) lookup, complements, frequency maps',
        description: "Hash maps unlock efficient O(1) lookup. They're central to the most important patterns.",
        skills: ['Dictionary lookup', 'Complement pattern', 'Frequency maps', 'Grouping by key', 'Seen-before tracking'],
        lessonCount: 4,
        problemCount: 8,
      },
      {
        id: 'p2-sets',
        order: 3,
        title: 'Sets',
        subtitle: 'uniqueness, fast lookup, visited tracking',
        description: 'A simple but powerful structure for tracking visited items and unique elements.',
        skills: ['Set creation', 'O(1) membership check', 'Duplicate removal', 'Visited tracking', 'Set operations'],
        lessonCount: 3,
        problemCount: 5,
      },
      {
        id: 'p2-stacks',
        order: 4,
        title: 'Stacks',
        subtitle: 'LIFO, parentheses matching, monotonic patterns',
        description: 'Stacks let you track what came before. Essential for matching problems and more.',
        skills: ['Push / pop', 'LIFO intuition', 'Parentheses matching', 'Monotonic stack intro', 'Stack-based history'],
        lessonCount: 4,
        problemCount: 7,
      },
      {
        id: 'p2-queues',
        order: 5,
        title: 'Queues and Deques',
        subtitle: 'FIFO, BFS setup, sliding operations',
        description: 'Queues process items in order — the foundation for BFS and level-order traversal.',
        skills: ['FIFO intuition', 'collections.deque', 'Queue-based processing', 'Sliding with deque', 'BFS foundation'],
        lessonCount: 4,
        problemCount: 6,
      },
      {
        id: 'p2-linked',
        order: 6,
        title: 'Linked Lists',
        subtitle: 'nodes, pointers, reversal, slow/fast',
        description: 'A classic interview structure. Pointer manipulation is a key skill you will use repeatedly.',
        skills: ['Node & next pointer', 'List traversal', 'Reversal', 'Slow & fast pointer', 'Cycle detection intro'],
        lessonCount: 5,
        problemCount: 8,
      },
      {
        id: 'p2-trees',
        order: 7,
        title: 'Trees',
        subtitle: 'binary trees, DFS, BFS, traversal patterns',
        description: 'Trees appear in ~25% of interviews. Learn to navigate and recurse through them.',
        skills: ['Binary tree structure', 'DFS (recursive)', 'BFS (queue-based)', 'Inorder / preorder / postorder', 'Traversal patterns'],
        lessonCount: 6,
        problemCount: 10,
      },
      {
        id: 'p2-heaps',
        order: 8,
        title: 'Heaps and Priority Queues',
        subtitle: 'min heap, top k, priority processing',
        description: 'Heaps efficiently track the smallest or largest element — key for top-K problems.',
        skills: ['heapq in Python', 'Min heap operations', 'Max heap workaround', 'Top K pattern', 'Priority ordering'],
        lessonCount: 4,
        problemCount: 7,
      },
      {
        id: 'p2-graphs',
        order: 9,
        title: 'Graph Basics',
        subtitle: 'adjacency list, BFS, DFS, components',
        description: 'Graphs model connected systems. Learn traversal before tackling graph-heavy interviews.',
        skills: ['Adjacency list', 'BFS on graphs', 'DFS on graphs', 'Visited set', 'Connected components'],
        lessonCount: 5,
        problemCount: 8,
      },
    ],
  },

  // ── PATH 3 ──────────────────────────────────────────────────────────────────
  {
    id: 'pattern-library',
    order: 3,
    title: 'Pattern Library',
    description: 'Every interview problem maps to a reusable pattern. Learn them all here.',
    blocks: [
      {
        id: 'p3-twopointers',
        order: 1,
        title: 'Two Pointers',
        subtitle: 'inward, slow/fast, partition',
        description: 'Use two index variables to scan arrays efficiently — eliminates nested loops.',
        skills: ['Inward pointers', 'Same-direction pointers', 'Slow & fast pointers', 'Partition-style problems'],
        lessonCount: 3,
        problemCount: 10,
      },
      {
        id: 'p3-window',
        order: 2,
        title: 'Sliding Window',
        subtitle: 'fixed window, variable window, substring tracking',
        description: 'Compute results over contiguous subarrays without redundant work.',
        skills: ['Fixed-size window', 'Variable-size window', 'Expand & contract logic', 'Char frequency in window'],
        lessonCount: 3,
        problemCount: 9,
      },
      {
        id: 'p3-prefix',
        order: 3,
        title: 'Prefix Sum',
        subtitle: 'cumulative sums, range queries, subarray insights',
        description: 'Precompute cumulative totals to answer range queries in O(1) instead of O(n).',
        skills: ['Prefix sum array', 'Range sum queries', 'Subarray sum', 'Prefix + hash map combo'],
        lessonCount: 3,
        problemCount: 7,
      },
      {
        id: 'p3-bsearch',
        order: 4,
        title: 'Binary Search',
        subtitle: 'search space, bounds, answer binary search',
        description: 'Narrow down a sorted search space by half each step — fast and elegant.',
        skills: ['Standard binary search', 'Left & right bounds', 'Search space reduction', 'Binary search on answer'],
        lessonCount: 4,
        problemCount: 10,
      },
      {
        id: 'p3-hashing',
        order: 5,
        title: 'Hashing Patterns',
        subtitle: 'complements, frequency, seen-before, grouping',
        description: 'Recurring hash map patterns that appear across dozens of common problems.',
        skills: ['Two-sum complement', 'Frequency counting', 'Seen-before', 'Group by key', 'Anagram detection'],
        lessonCount: 3,
        problemCount: 9,
      },
      {
        id: 'p3-stackpat',
        order: 6,
        title: 'Stack Patterns',
        subtitle: 'matching, monotonic stack, next greater element',
        description: 'Advanced stack usage: monotonic stacks and sequence reasoning.',
        skills: ['Bracket matching', 'Monotonic decreasing stack', 'Next greater element', 'Daily temperatures style'],
        lessonCount: 3,
        problemCount: 8,
      },
      {
        id: 'p3-bfs',
        order: 7,
        title: 'BFS Patterns',
        subtitle: 'level order, shortest path, grid BFS',
        description: 'Breadth-first search for shortest paths and level-by-level exploration.',
        skills: ['Level-order traversal', 'Shortest path (unweighted)', 'Grid BFS', 'Multi-source BFS'],
        lessonCount: 4,
        problemCount: 10,
      },
      {
        id: 'p3-dfs',
        order: 8,
        title: 'DFS and Backtracking',
        subtitle: 'subsets, permutations, path exploration',
        description: 'Explore all possibilities recursively. The basis for combination and path problems.',
        skills: ['Recursive DFS', 'Backtracking template', 'Subsets generation', 'Permutations', 'Constraint pruning'],
        lessonCount: 4,
        problemCount: 12,
      },
      {
        id: 'p3-treepat',
        order: 9,
        title: 'Tree Patterns',
        subtitle: 'recursive DFS, depth/diameter, subtrees',
        description: 'Systematic patterns for tree problems: recursive decomposition and tree-level reasoning.',
        skills: ['Recursive DFS pattern', 'Tree height & depth', 'Diameter calculation', 'Subtree logic', 'Path problems'],
        lessonCount: 4,
        problemCount: 10,
      },
      {
        id: 'p3-heappat',
        order: 10,
        title: 'Heap Patterns',
        subtitle: 'top k, running median, repeated extraction',
        description: 'Heap-based patterns for problems requiring repeated access to extremes.',
        skills: ['Top K elements', 'K closest points', 'Running median (two heaps)', 'Merge K sorted lists'],
        lessonCount: 3,
        problemCount: 8,
      },
      {
        id: 'p3-dp',
        order: 11,
        title: 'Dynamic Programming Intro',
        subtitle: 'memoization, tabulation, 1D DP',
        description: 'Solve complex problems by breaking them into overlapping subproblems. The most-feared pattern — demystified.',
        skills: ['Overlapping subproblems', 'Memoization (top-down)', 'Tabulation (bottom-up)', '1D DP basics', 'State transitions'],
        lessonCount: 5,
        problemCount: 10,
      },
    ],
  },

  // ── PATH 4 ──────────────────────────────────────────────────────────────────
  {
    id: 'interview-ready',
    order: 4,
    title: 'Interview Ready',
    description: 'Turn pattern knowledge into consistent interview performance.',
    blocks: [
      {
        id: 'p4-breakdown',
        order: 1,
        title: 'Problem Breakdown Framework',
        subtitle: 'read, identify, plan, execute',
        description: 'A repeatable process for approaching any problem you have never seen before.',
        skills: ['Reading problem statements', 'Identifying inputs & outputs', 'Constraint analysis', 'Pattern recognition checklist', 'Planning before coding'],
        lessonCount: 4,
        problemCount: 5,
      },
      {
        id: 'p4-optimize',
        order: 2,
        title: 'Brute Force to Optimal',
        subtitle: 'start naive, improve step by step',
        description: 'Start with the obvious solution, then systematically improve it.',
        skills: ['Brute force first', 'Identifying bottlenecks', 'Improving time complexity', 'Communicating tradeoffs'],
        lessonCount: 3,
        problemCount: 8,
      },
      {
        id: 'p4-clean',
        order: 3,
        title: 'Writing Clean Interview Code',
        subtitle: 'naming, helpers, edge cases, readability',
        description: 'Code quality matters in interviews. Learn to write clear, correct code under pressure.',
        skills: ['Variable naming', 'Helper functions', 'Edge case handling', 'Readable structure', 'Avoiding common mistakes'],
        lessonCount: 3,
        problemCount: 5,
      },
      {
        id: 'p4-testing',
        order: 4,
        title: 'Testing and Debugging',
        subtitle: 'dry runs, custom cases, off-by-one',
        description: 'Validate your code before you submit. Interviewers love candidates who test their own work.',
        skills: ['Manual trace / dry run', 'Custom test cases', 'Common bug patterns', 'Off-by-one errors', 'Empty/single-element edge cases'],
        lessonCount: 3,
        problemCount: 5,
      },
      {
        id: 'p4-easy',
        order: 5,
        title: 'Timed Easy Interviews',
        subtitle: 'speed, clarity, easy round practice',
        description: 'Practice under real time pressure. Easy rounds should be solved fast and explained cleanly.',
        skills: ['Time management', 'Fast pattern recognition', 'Clean explanation', 'Confidence building'],
        lessonCount: 1,
        problemCount: 15,
      },
      {
        id: 'p4-medium',
        order: 6,
        title: 'Timed Medium Interviews',
        subtitle: 'realistic pacing, pattern recall under pressure',
        description: 'Medium problems are the real benchmark. Practice pattern recall at speed.',
        skills: ['Medium problem pacing', 'Pattern recognition under stress', 'Communicating while coding', 'Managing hints'],
        lessonCount: 1,
        problemCount: 15,
      },
      {
        id: 'p4-communication',
        order: 7,
        title: 'Communication and Explanation',
        subtitle: 'talking through approach, complexity',
        description: 'How you explain matters as much as what you write. Think out loud effectively.',
        skills: ['Talking through approach', 'Time complexity explanation', 'Space complexity explanation', 'Asking clarifying questions'],
        lessonCount: 3,
        problemCount: 5,
      },
      {
        id: 'p4-review',
        order: 8,
        title: 'Review and Weak Spot Targeting',
        subtitle: 'revisit weak blocks, targeted reinforcement',
        description: 'Identify and fix the gaps in your knowledge before the real interview.',
        skills: ['Identifying weak patterns', 'Targeted re-practice', 'Pattern reinforcement', 'Progress assessment'],
        lessonCount: 2,
        problemCount: 20,
      },
      {
        id: 'p4-final',
        order: 9,
        title: 'Final Interview Readiness Check',
        subtitle: 'benchmark problem set, full assessment',
        description: 'A curated set covering all major patterns. Pass this and you are ready.',
        skills: ['Full pattern coverage', 'Mixed difficulty', 'Timed benchmark', 'Readiness score'],
        lessonCount: 1,
        problemCount: 25,
      },
    ],
  },
];
