export const PRO_MONTHLY_USD = 9;
export const PRO_YEARLY_USD = 59;
export const PRO_YEARLY_FULL_USD = PRO_MONTHLY_USD * 12;
export const PRO_YEARLY_SAVINGS_USD = PRO_YEARLY_FULL_USD - PRO_YEARLY_USD;
export const PRO_YEARLY_SAVINGS_PCT = Math.round(
  (PRO_YEARLY_SAVINGS_USD / PRO_YEARLY_FULL_USD) * 100,
);
export const PRO_YEARLY_PER_MONTH_USD = PRO_YEARLY_USD / 12;

export const MONTHLY_PRICE_LABEL = `$${PRO_MONTHLY_USD}`;
export const YEARLY_PRICE_LABEL = `$${PRO_YEARLY_USD}`;
export const YEARLY_FULL_LABEL = `$${PRO_YEARLY_FULL_USD}`;
export const YEARLY_SAVINGS_LABEL = `$${PRO_YEARLY_SAVINGS_USD}`;
export const YEARLY_SAVINGS_PCT_LABEL = `${PRO_YEARLY_SAVINGS_PCT}%`;
export const YEARLY_PER_MONTH_LABEL = `$${PRO_YEARLY_PER_MONTH_USD.toFixed(2)}`;
