// ─── Quick Review Card Types & Data ─────────────────────────────────────────

export type QuickCardType = 'big_o' | 'pattern' | 'code_reading';

export type InteractionMode = 'mcq' | 'type_answer' | 'reveal';

export interface QuickCard {
  id: string;
  type: QuickCardType;
  title: string;
  question: string;
  answer: string;
  code?: string;
  interaction: InteractionMode;
  choices?: string[];
  correctChoice?: number;
  typePrompt?: string;
  acceptableAnswers?: string[];
}

export const QUICK_CARDS: QuickCard[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // BIG-O QUESTIONS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'qr-bigo-1',
    type: 'big_o',
    title: 'Array: Access by Index',
    question: 'What is the time complexity of accessing an element by index in an array?',
    answer: 'O(1) -- Arrays store elements in contiguous memory. Index access computes the memory address directly: base + (index * element_size). No iteration needed.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 0,
  },
  {
    id: 'qr-bigo-2',
    type: 'big_o',
    title: 'Array: Search (Unsorted)',
    question: 'What is the time complexity of searching for a value in an unsorted array?',
    answer: 'O(n) -- Without any ordering, you must check every element in the worst case. There is no shortcut to skip elements.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-3',
    type: 'big_o',
    title: 'Array: Insert at Beginning',
    question: 'What is the time complexity of inserting at the beginning of a dynamic array?',
    answer: 'O(n) -- Every existing element must shift one position to the right to make room at index 0.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-4',
    type: 'big_o',
    title: 'Hash Map: Average Lookup',
    question: 'What is the average time complexity of looking up a key in a hash map?',
    answer: 'O(1) average -- The hash function maps keys to bucket indices directly. Worst case is O(n) when all keys collide into the same bucket.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 0,
  },
  {
    id: 'qr-bigo-5',
    type: 'big_o',
    title: 'Merge Sort',
    question: 'What is the time complexity of Merge Sort?',
    answer: 'O(n log n) -- The array is split in half log(n) times, and each level does O(n) work to merge. Space complexity is O(n) for the auxiliary arrays.',
    interaction: 'mcq',
    choices: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-6',
    type: 'big_o',
    title: 'Binary Search',
    question: 'What is the time complexity of binary search on a sorted array?',
    answer: 'O(log n) -- Each comparison eliminates half the remaining elements. After log(n) comparisons, only one element remains.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-7',
    type: 'big_o',
    title: 'BFS / DFS on a Graph',
    question: 'What is the time complexity of BFS or DFS on a graph with V vertices and E edges (adjacency list)?',
    answer: 'O(V + E) -- Every vertex is visited once, and every edge is examined once. An adjacency matrix would be O(V^2) since you check every possible edge.',
    interaction: 'mcq',
    choices: ['O(V)', 'O(E)', 'O(V + E)', 'O(V * E)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-10',
    type: 'big_o',
    title: 'Linked List Head Insertion',
    question: 'What is the time complexity of inserting a node at the head of a singly linked list?',
    answer: 'O(1). Inserting at the head only requires creating a new node and updating the head pointer -- no traversal is needed regardless of list size.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 0,
  },
  {
    id: 'qr-bigo-11',
    type: 'big_o',
    title: 'Linked List Value Lookup',
    question: 'What is the time complexity of searching for a specific value in an unsorted singly linked list of n elements?',
    answer: 'O(n). There is no random access in a linked list, so you must traverse nodes one by one from the head. In the worst case the value is at the end or not present.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-12',
    type: 'big_o',
    title: 'Linked List Node Removal',
    question: 'Given a direct reference to a node in a doubly linked list, what is the time complexity of deleting that node?',
    answer: 'O(1). With a direct reference to the node and back-pointers available, you simply update the previous and next neighbors to point to each other. No search or traversal is required.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctChoice: 0,
  },
  {
    id: 'qr-bigo-13',
    type: 'big_o',
    title: 'Stack Push and Pop',
    question: 'What is the time complexity of push and pop operations on a stack (implemented with an array or linked list)?',
    answer: 'O(1). Both push and pop operate only on the top of the stack. No elements need to be shifted or traversed.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 0,
  },
  {
    id: 'qr-bigo-14',
    type: 'big_o',
    title: 'Queue Operations via Linked List',
    question: 'What is the time complexity of enqueue and dequeue on a queue implemented with a linked list (with head and tail pointers)?',
    answer: 'O(1). Enqueue appends at the tail pointer and dequeue removes from the head pointer. Both are constant-time pointer updates with no traversal needed.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctChoice: 0,
  },
  {
    id: 'qr-bigo-15',
    type: 'big_o',
    title: 'Heap Insertion',
    question: 'What is the time complexity of inserting an element into a binary heap with n elements?',
    answer: 'O(log n). The new element is placed at the bottom of the heap and then "bubbled up" by swapping with its parent. The heap has log n levels, so at most log n swaps are needed.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-16',
    type: 'big_o',
    title: 'Heap Extract Operation',
    question: 'What is the time complexity of extracting the minimum (or maximum) element from a binary heap of n elements?',
    answer: 'O(log n). The root is removed and replaced by the last element, which is then "sifted down" through at most log n levels to restore the heap property.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-17',
    type: 'big_o',
    title: 'Building a Heap from an Array',
    question: 'What is the time complexity of building a binary heap from an unsorted array of n elements using the heapify algorithm?',
    answer: 'O(n). Although each sift-down is O(log n), most nodes are near the bottom and sift down very few levels. A mathematical analysis shows the total work sums to O(n), not O(n log n).',
    interaction: 'mcq',
    choices: ['O(log n)', 'O(n)', 'O(n log n)', 'O(n^2)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-18',
    type: 'big_o',
    title: 'Trie Word Insertion',
    question: 'What is the time complexity of inserting a word of length L into a trie?',
    answer: 'O(L). You traverse or create one node per character in the word. The operation depends only on the length of the word, not on how many words are already in the trie.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(L)', 'O(n)', 'O(n * L)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-19',
    type: 'big_o',
    title: 'Balanced BST Search',
    question: 'What is the time complexity of searching for a value in a balanced binary search tree (e.g. AVL tree) with n nodes?',
    answer: 'O(log n). Balancing guarantees the tree height is O(log n). Each comparison eliminates half the remaining nodes.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-20',
    type: 'big_o',
    title: 'Balanced BST Insertion',
    question: 'What is the time complexity of inserting a value into a balanced BST (e.g. AVL tree) with n nodes?',
    answer: 'O(log n). The insertion itself takes O(log n) to find the correct position. Rebalancing (rotations) after insertion takes O(1) for AVL trees, so the overall cost is O(log n).',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-21',
    type: 'big_o',
    title: 'Python List Append Cost',
    question: 'What is the amortized time complexity of Python\'s list.append() operation?',
    answer: 'O(1) amortized. Python lists use a dynamic array that over-allocates space. Most appends simply place the element in pre-allocated memory. Occasionally the array must be resized (an O(n) copy), but this cost is spread across many appends.',
    interaction: 'mcq',
    choices: ['O(1) amortized', 'O(log n)', 'O(n)', 'O(n) amortized'],
    correctChoice: 0,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PATTERN RECOGNITION QUESTIONS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'qr-pattern-1',
    type: 'pattern',
    title: 'Sorted Array Pair Sum',
    question: 'You have a SORTED array and need to find two numbers that sum to a target in O(n) time. Which approach takes advantage of the sort order?',
    answer: 'Two Pointers -- Place one pointer at the start and one at the end. If the sum is too small, move the left pointer right. If too big, move the right pointer left. O(n) time, O(1) space.\n\nA hash map also works for pair sum in O(n) time, but it uses O(n) space and doesn\'t leverage the sorted property.',
    interaction: 'mcq',
    choices: ['Sliding Window', 'Two Pointers', 'Binary Search on each element', 'Brute Force nested loops'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-2',
    type: 'pattern',
    title: 'Contiguous Subarray',
    question: 'You need to find the longest contiguous substring with at most k distinct characters. What pattern is this?',
    answer: 'Sliding Window -- Maintain a window [left, right] with a frequency map. Expand right to add characters; when distinct count exceeds k, shrink from the left. Each element is added/removed at most once, so it runs in O(n).',
    interaction: 'mcq',
    choices: ['Two Pointers', 'Dynamic Programming', 'Sliding Window', 'Backtracking'],
    correctChoice: 2,
  },
  {
    id: 'qr-pattern-3',
    type: 'pattern',
    title: 'Shortest Path (Unweighted)',
    question: 'You need to find the minimum number of moves to reach a target in a grid where each move costs the same. Which traversal guarantees the shortest path?',
    answer: 'BFS -- BFS explores all nodes at the current depth before moving deeper, so the first time it reaches any node is via the shortest path. DFS may find a path, but not necessarily the shortest one.',
    interaction: 'mcq',
    choices: ['DFS with backtracking', 'BFS', 'Dijkstra\'s Algorithm', 'Topological Sort'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-4',
    type: 'pattern',
    title: 'Fibonacci-style Problem',
    question: 'You\'re computing the number of ways to climb n stairs, taking 1 or 2 steps at a time. The answer for n depends on answers for n-1 and n-2, and these sub-problems repeat. What technique should you use?',
    answer: 'Dynamic Programming -- This has both required properties:\n1. Optimal substructure: ways(n) = ways(n-1) + ways(n-2)\n2. Overlapping subproblems: ways(3) is needed by both ways(4) and ways(5)\n\nWithout memoization, the naive recursion is O(2^n). With DP it\'s O(n).',
    interaction: 'mcq',
    choices: [
      'Greedy algorithm',
      'Dynamic Programming',
      'Divide and conquer',
      'Backtracking with pruning',
    ],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-5',
    type: 'pattern',
    title: 'Next Greater Element',
    question: 'For each element in an array, you need to find the next element to its right that is strictly greater. What data structure gives you O(n) total time?',
    answer: 'Monotonic Stack -- Iterate left to right, maintaining a stack of elements (or indices) in decreasing order. When you see a larger element, pop everything smaller and record the answer for each popped item. Each element is pushed and popped at most once, so total work is O(n).',
    interaction: 'mcq',
    choices: ['Queue', 'Stack', 'Heap / Priority Queue', 'Balanced BST'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-10',
    type: 'pattern',
    title: 'Linked List Cycle Detection',
    question: 'You have a singly linked list and need to determine if it contains a cycle. You want O(1) space complexity. Which technique should you use?',
    answer: 'Fast & Slow Pointers. By advancing one pointer by 1 step and another by 2 steps, if a cycle exists they will eventually meet. This avoids using a hash set (O(n) space) and solves it in O(n) time with O(1) space.',
    interaction: 'mcq',
    choices: ['Fast & Slow Pointers', 'Hash Map', 'Binary Search', 'Stack-based traversal'],
    correctChoice: 0,
  },
  {
    id: 'qr-pattern-11',
    type: 'pattern',
    title: 'Undirected Graph Grouping',
    question: 'Given n nodes and a list of undirected edges, you need to find how many connected components exist in the graph. Which technique is most appropriate?',
    answer: 'Union Find (Disjoint Set Union). It efficiently merges components as you process edges and can answer connectivity queries in near O(1). DFS can also traverse each component, but Union Find is the classic choice for grouping problems.',
    interaction: 'mcq',
    choices: ['Union Find', 'Topological Sort', 'Dijkstra\'s Algorithm', 'Binary Search'],
    correctChoice: 0,
  },
  {
    id: 'qr-pattern-12',
    type: 'pattern',
    title: 'Course Scheduling with Prerequisites',
    question: 'You have a list of courses and prerequisite pairs. You need to find a valid order to take all courses, or determine if it is impossible. Which technique should you use?',
    answer: 'Topological Sort. Prerequisites form a directed acyclic graph (DAG). Topological sort produces a linear ordering where for every edge u->v, u comes before v. If a cycle is detected, no valid ordering exists.',
    interaction: 'mcq',
    choices: ['BFS (level order)', 'Topological Sort', 'Union Find', 'Dynamic Programming'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-13',
    type: 'pattern',
    title: 'Subarray Sum Equals Target',
    question: 'Given an integer array (which may contain negative numbers) and a target K, you need to count contiguous subarrays whose elements sum to exactly K. Which technique should you use?',
    answer: 'Prefix Sum + Hash Map. Compute a running prefix sum and store the frequency of each sum in a hash map. At each index, check if (currentSum - K) exists. Sliding window does NOT work here because negative numbers prevent monotonic growth.',
    interaction: 'mcq',
    choices: ['Sliding Window', 'Prefix Sum + Hash Map', 'Two Pointers', 'Sorting + Binary Search'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-14',
    type: 'pattern',
    title: 'Generating Valid Parentheses',
    question: 'You need to generate all combinations of n pairs of well-formed parentheses. Which technique is best suited?',
    answer: 'Backtracking. Build the string character by character, choosing to add "(" or ")" at each step. Prune invalid states by tracking open and close counts, backtracking when a choice would lead to an invalid combination.',
    interaction: 'mcq',
    choices: ['Dynamic Programming', 'BFS (level order generation)', 'Backtracking', 'Greedy'],
    correctChoice: 2,
  },
  {
    id: 'qr-pattern-15',
    type: 'pattern',
    title: 'Minimum Coins for Change',
    question: 'Given coin denominations [1, 3, 4] and a target amount of 6, you need the minimum number of coins. Greedy gives 4+1+1 = 3 coins. Can you do better?',
    answer: 'Dynamic Programming. The optimal is 3+3 = 2 coins. Greedy (always pick the largest coin) fails for many denomination sets. DP builds up solutions for every sub-amount, guaranteeing the true minimum.',
    interaction: 'mcq',
    choices: ['Greedy (largest coin first)', 'Dynamic Programming', 'Backtracking', 'BFS on a graph'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-16',
    type: 'pattern',
    title: 'Maximum Non-Overlapping Intervals',
    question: 'Given activities with start and end times, you want to select the maximum number of non-overlapping activities. Which technique should you use?',
    answer: 'Greedy. Sort intervals by end time and greedily pick each activity that starts after the last selected one ends. This classic activity selection problem has an optimal greedy solution because locally optimal choices (earliest finish) lead to a globally optimal result.',
    interaction: 'mcq',
    choices: ['Dynamic Programming', 'Greedy', 'Divide and Conquer', 'Backtracking'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-17',
    type: 'pattern',
    title: 'Streaming Median Finder',
    question: 'You are receiving integers one at a time from a data stream and need to efficiently return the median after each insertion. Which data structure should you use?',
    answer: 'Two Heaps (a max-heap for the lower half and a min-heap for the upper half). By keeping both heaps balanced in size, the median is always available from the tops of the heaps in O(1), with O(log n) insertion.',
    interaction: 'mcq',
    choices: ['Sorted Array with Binary Insertion', 'Two Heaps (max-heap + min-heap)', 'Balanced BST', 'Quickselect on each query'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-18',
    type: 'pattern',
    title: 'Merging K Sorted Lists',
    question: 'You have K sorted linked lists and need to merge them into one sorted list. Which approach is most efficient?',
    answer: 'Heap / Priority Queue (min-heap). Insert the head of each list into a min-heap. Repeatedly extract the minimum, append it to the result, and insert that node\'s next element. This runs in O(N log K) where N is the total number of elements.',
    interaction: 'mcq',
    choices: ['Merge all then sort', 'Heap / Priority Queue', 'Merge Sort (pairwise)', 'Linked List splicing with two pointers'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-19',
    type: 'pattern',
    title: 'Almost-Palindrome Validation',
    question: 'Given a string, determine if it can become a palindrome by removing at most one character. Which technique should you use?',
    answer: 'Two Pointers. Start pointers at both ends and move inward. When a mismatch is found, try skipping either the left or right character and check if the remaining substring is a palindrome. O(n) time, O(1) space.',
    interaction: 'mcq',
    choices: ['Dynamic Programming (LPS)', 'Two Pointers', 'Recursion with memoization', 'Hash Map character counting'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-20',
    type: 'pattern',
    title: 'Word Search in a Grid',
    question: 'Given a 2D grid of characters and a target word, determine if the word exists by following adjacent cells (no cell reused). Which technique should you use?',
    answer: 'DFS + Backtracking. Start DFS from each cell matching the first character. At each step, mark the cell as visited and explore all four directions. If a path fails, backtrack by unmarking the cell.',
    interaction: 'mcq',
    choices: ['BFS with queue', 'DFS + Backtracking', 'Trie-based search', 'Dynamic Programming'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-21',
    type: 'pattern',
    title: 'Trapping Rain Water',
    question: 'Given an array of non-negative integers representing an elevation map, compute how much water can be trapped after raining. Which technique should you use?',
    answer: 'Two Pointers. Track the max height seen from each side, computing trapped water in O(n) time and O(1) space. A monotonic stack approach also works in O(n) time but uses O(n) space.',
    interaction: 'mcq',
    choices: ['Sliding Window', 'Two Pointers', 'Prefix/Suffix Arrays only', 'Greedy with sorting'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-1',
    type: 'pattern',
    title: 'Map Implementation Choice',
    question: 'You need a key-value store with the fastest possible lookups and you do NOT need keys in sorted order. Which should you use?',
    answer: 'HashMap. It provides O(1) average-case lookup via hashing, while TreeMap provides O(log n) because it maintains sorted order using a balanced BST. If you don\'t need ordering, HashMap is the better choice.',
    interaction: 'mcq',
    choices: ['TreeMap -- balanced tree gives consistent performance', 'HashMap -- O(1) average lookup when order is not needed', 'LinkedHashMap -- insertion order is always required', 'SortedSet -- sets are faster than maps'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-2',
    type: 'pattern',
    title: 'Data Structure for Middle Insertions',
    question: 'You need to frequently insert and delete elements in the MIDDLE of a collection. Which data structure is more efficient for the insert/delete itself?',
    answer: 'Linked List. Inserting or deleting in the middle of an array requires shifting all subsequent elements -- O(n). A linked list only requires updating a few pointers -- O(1) once you have a reference to the node. The tradeoff: linked lists have O(n) access by index.',
    interaction: 'mcq',
    choices: ['Array -- contiguous memory makes all operations fast', 'Linked List -- pointer updates avoid shifting elements', 'Stack -- LIFO structure optimizes middle operations', 'Hash Map -- hashing allows O(1) insertion anywhere'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-3',
    type: 'pattern',
    title: 'Graph Representation for Sparse Graphs',
    question: 'For a graph with 10,000 vertices but only 15,000 edges, which representation is more space-efficient?',
    answer: 'Adjacency list. It uses O(V + E) space (~25,000). An adjacency matrix uses O(V^2) (100,000,000). Adjacency matrices are only space-efficient when the graph is dense (E approaches V^2).',
    interaction: 'mcq',
    choices: ['Adjacency matrix -- O(V^2) is fine for any graph', 'Edge list -- storing pairs is always most compact', 'Adjacency list -- O(V + E) is far smaller for sparse graphs', 'Incidence matrix -- it compresses better'],
    correctChoice: 2,
  },
  {
    id: 'qr-concept-4',
    type: 'pattern',
    title: 'Quick Sort Worst Case',
    question: 'Under what condition does Quick Sort degrade from O(n log n) to O(n^2)?',
    answer: 'When the pivot selection consistently produces maximally unbalanced partitions -- e.g., always picking the first element on an already-sorted array. Each partition only removes one element, leading to n levels of recursion with O(n) work each. Randomized pivot selection avoids this in practice.',
    interaction: 'mcq',
    choices: ['When the array contains duplicate values', 'When the array is already sorted and the pivot is always the first or last element', 'When the array size exceeds available memory', 'When the array contains negative numbers'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-5',
    type: 'pattern',
    title: 'Auxiliary Structure for DFS',
    question: 'When implementing DFS iteratively (without recursion), which data structure replaces the call stack?',
    answer: 'A stack (LIFO). DFS explores as deep as possible before backtracking -- this matches LIFO behavior perfectly. The last node pushed is the first explored, mirroring how recursive calls unwind. A queue (FIFO) would give you BFS instead.',
    interaction: 'mcq',
    choices: ['Queue -- FIFO order ensures full depth exploration', 'Stack -- LIFO order matches DFS backtracking behavior', 'Priority Queue -- ordering nodes by depth is required', 'Deque -- bidirectional access is needed'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-6',
    type: 'pattern',
    title: 'Finding the K Largest Elements',
    question: 'You need the top 5 largest elements from a list of 1,000,000 items. What is the most efficient approach?',
    answer: 'Use a min-heap of size 5. Iterate through all elements: if the current element is larger than the heap\'s minimum, replace it. O(n log k) time. Sorting would cost O(n log n), which is significantly more when k << n.',
    interaction: 'mcq',
    choices: ['Sort the entire array and take the last 5', 'Use a min-heap of size k -- O(n log k)', 'Use a max-heap of all elements and extract 5 times', 'Use binary search to find the 5th largest'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-7',
    type: 'pattern',
    title: 'Recursion vs Iteration Tradeoff',
    question: 'When is a recursive solution problematic compared to an equivalent iterative one?',
    answer: 'When the recursion depth is very large (e.g., processing a linked list of 100,000 nodes). Each recursive call adds a frame to the call stack, and most languages limit stack size (~10,000 frames). Exceeding this causes a stack overflow. An iterative loop uses constant stack space.',
    interaction: 'mcq',
    choices: ['When the problem has overlapping subproblems', 'When the input size could cause recursion depth to exceed the call stack limit', 'When the function has more than two parameters', 'When the base case returns a non-primitive type'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-8',
    type: 'pattern',
    title: 'Set Lookup Time Complexity',
    question: 'Why does a HashSet provide O(1) average lookup while a TreeSet provides O(log n)?',
    answer: 'A HashSet computes a hash and jumps directly to the correct bucket -- constant time on average. A TreeSet stores elements in a balanced BST, so lookup requires traversing from root to leaf -- O(log n). The tradeoff: TreeSet keeps elements sorted, HashSet does not.',
    interaction: 'mcq',
    choices: ['HashSet uses more memory, which makes it faster', 'HashSet uses hashing for direct access; TreeSet uses tree traversal requiring O(log n) comparisons', 'TreeSet is O(log n) because it must rebalance on every lookup', 'HashSet is only O(1) for integers; for strings it is also O(log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-concept-9',
    type: 'pattern',
    title: 'Deque vs Standard Queue',
    question: 'In a sliding window maximum problem, why is a deque preferred over a standard queue?',
    answer: 'A deque allows adding and removing from BOTH ends in O(1). For sliding window maximum, you need to: (1) remove from the front when elements leave the window, and (2) remove from the back elements smaller than the new one to maintain decreasing order. A standard queue only supports removal from the front.',
    interaction: 'mcq',
    choices: ['A deque is faster because it uses a linked list', 'A deque allows O(1) insertion and removal from both ends', 'A standard queue cannot hold more than a fixed number of elements', 'A deque automatically sorts elements in decreasing order'],
    correctChoice: 1,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CODE READING QUESTIONS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'qr-code-1',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this function return for nums = [2, 7, 11, 15] and target = 9?',
    code: 'def solve(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        comp = target - n\n        if comp in seen:\n            return [seen[comp], i]\n        seen[n] = i\n    return []',
    answer: '[0, 1] -- This is the Two Sum pattern using a hash map.\n\ni=0: n=2, comp=7, not in seen, store {2:0}\ni=1: n=7, comp=2, 2 IS in seen, return [0, 1]\n\nIndices 0 and 1 point to values 2 and 7, which sum to 9.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (e.g. [0, 1])',
    acceptableAnswers: ['[0, 1]', '[0,1]', '0, 1', '0,1'],
  },
  {
    id: 'qr-code-2',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for s = "abcabcbb"?',
    code: 'def solve(s):\n    seen = set()\n    l = ans = 0\n    for r in range(len(s)):\n        while s[r] in seen:\n            seen.remove(s[l])\n            l += 1\n        seen.add(s[r])\n        ans = max(ans, r - l + 1)\n    return ans',
    answer: '3 -- This is the Sliding Window pattern for longest substring without repeating characters.\n\nThe longest non-repeating substring is "abc" (length 3). When a duplicate is found, the left pointer shrinks the window until the duplicate is removed.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['3'],
  },
  {
    id: 'qr-code-3',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [3, 2, 1, 5, 6, 4] and k = 2?',
    code: 'import heapq\n\ndef solve(nums, k):\n    heap = []\n    for n in nums:\n        heapq.heappush(heap, n)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap[0]',
    answer: '5 -- This finds the kth largest element using a min-heap of size k.\n\nThe heap keeps the k largest values seen so far. The smallest of those (the root) is the kth largest overall.\n\nAfter processing all elements, heap = [5, 6]. heap[0] = 5 (2nd largest).\n\nTime: O(n log k), Space: O(k)',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['5'],
  },
  {
    id: 'qr-code-4',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'def solve(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1',
    answer: 'Binary Search -- The code repeatedly halves the search space by comparing the middle element to the target. If the middle is too small, search the right half; if too large, search the left half.\n\nTime: O(log n), Space: O(1)',
    interaction: 'mcq',
    choices: ['Two Pointers', 'Binary Search', 'Sliding Window', 'Divide and Conquer'],
    correctChoice: 1,
  },
  {
    id: 'qr-code-5',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for head = 1->2->3->4?',
    code: 'def solve(head):\n    prev = None\n    curr = head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev = curr\n        curr = nxt\n    return prev',
    answer: '4->3->2->1 -- This reverses a linked list iteratively.\n\nprev=None, curr=1: point 1.next to None, prev=1, curr=2\nprev=1, curr=2: point 2.next to 1, prev=2, curr=3\nprev=2, curr=3: point 3.next to 2, prev=3, curr=4\nprev=3, curr=4: point 4.next to 3, prev=4, curr=None\n\nReturn prev = node 4, chain 4->3->2->1.',
    interaction: 'type_answer',
    typePrompt: 'Type the resulting list (e.g. 4->3->2->1)',
    acceptableAnswers: ['4->3->2->1', '[4, 3, 2, 1]', '[4,3,2,1]', '4,3,2,1'],
  },
  {
    id: 'qr-code-6',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for grid = [["1","1","0"],["1","0","0"],["0","0","1"]]?',
    code: 'def solve(grid):\n    rows, cols = len(grid), len(grid[0])\n    count = 0\n    def dfs(r, c):\n        if r < 0 or r >= rows or c < 0 or c >= cols:\n            return\n        if grid[r][c] != "1":\n            return\n        grid[r][c] = "0"\n        for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n            dfs(r + dr, c + dc)\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == "1":\n                count += 1\n                dfs(r, c)\n    return count',
    answer: '2 -- This counts islands using DFS flood fill.\n\nIsland 1: cells (0,0), (0,1), (1,0) -- connected\nIsland 2: cell (2,2) -- isolated\n\nEach time we find an unvisited "1", we increment count and DFS-mark the whole island as visited.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['2'],
  },
  {
    id: 'qr-code-7',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for height = [1, 8, 6, 2, 5, 4, 8, 3, 7]?',
    code: 'def solve(height):\n    l, r = 0, len(height) - 1\n    best = 0\n    while l < r:\n        w = r - l\n        h = min(height[l], height[r])\n        best = max(best, w * h)\n        if height[l] < height[r]:\n            l += 1\n        else:\n            r -= 1\n    return best',
    answer: '49 -- This is the Container With Most Water two-pointer approach.\n\nThe optimal container uses indices 1 and 8 (values 8 and 7).\nWidth = 8 - 1 = 7, height = min(8, 7) = 7, area = 7 * 7 = 49.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['49'],
  },
  {
    id: 'qr-code-8',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'from collections import deque\n\ndef solve(n, edges):\n    adj = [[] for _ in range(n)]\n    indeg = [0] * n\n    for u, v in edges:\n        adj[u].append(v)\n        indeg[v] += 1\n    q = deque(i for i in range(n) if indeg[i] == 0)\n    order = []\n    while q:\n        node = q.popleft()\n        order.append(node)\n        for nei in adj[node]:\n            indeg[nei] -= 1\n            if indeg[nei] == 0:\n                q.append(nei)\n    return order if len(order) == n else []',
    answer: 'Topological Sort (Kahn\'s Algorithm) -- Builds an in-degree table, seeds a queue with zero-in-degree nodes, and peels them off layer by layer. Each removed node decrements its neighbors\' in-degrees. If the final order has all n nodes, the graph is a valid DAG.\n\nTime: O(V + E)',
    interaction: 'mcq',
    choices: ['BFS (Level Order)', 'Topological Sort (Kahn\'s Algorithm)', 'Shortest Path (BFS)', 'Strongly Connected Components'],
    correctChoice: 1,
  },
  {
    id: 'qr-code-9',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'def solve(n, edges):\n    parent = list(range(n))\n    rank = [0] * n\n    def find(x):\n        while parent[x] != x:\n            parent[x] = parent[parent[x]]\n            x = parent[x]\n        return x\n    def union(a, b):\n        ra, rb = find(a), find(b)\n        if ra == rb:\n            return False\n        if rank[ra] < rank[rb]:\n            ra, rb = rb, ra\n        parent[rb] = ra\n        if rank[ra] == rank[rb]:\n            rank[ra] += 1\n        return True\n    return all(union(u, v) for u, v in edges)',
    answer: 'Union-Find / Disjoint Set Union -- Maintains a parent array with path compression and union by rank. find() locates the root representative, union() merges two sets. Returns False if an edge connects two already-connected nodes (cycle detection).',
    interaction: 'mcq',
    choices: ['Graph Coloring', 'Union-Find / Disjoint Set', 'Adjacency List BFS', 'Minimum Spanning Tree (Prim\'s)'],
    correctChoice: 1,
  },
  {
    id: 'qr-code-10',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for n = 7?',
    code: 'def solve(n):\n    memo = {}\n    def fib(k):\n        if k in memo:\n            return memo[k]\n        if k <= 1:\n            return k\n        memo[k] = fib(k - 1) + fib(k - 2)\n        return memo[k]\n    return fib(n)',
    answer: '13 -- This computes Fibonacci with memoization (top-down DP).\n\nfib(0)=0, fib(1)=1, fib(2)=1, fib(3)=2, fib(4)=3, fib(5)=5, fib(6)=8, fib(7)=13\n\nThe memo dict caches results so each fib(k) is computed only once. Time: O(n).',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['13'],
  },
  {
    id: 'qr-code-11',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for s = "({[]})"?',
    code: 'def solve(s):\n    stack = []\n    pairs = {")": "(", "]": "[", "}": "{"}\n    for ch in s:\n        if ch in pairs:\n            if not stack or stack[-1] != pairs[ch]:\n                return False\n            stack.pop()\n        else:\n            stack.append(ch)\n    return len(stack) == 0',
    answer: 'True -- This is the Valid Parentheses checker using a stack.\n\n"(" push, "{" push, "[" push, "]" matches "[" pop, "}" matches "{" pop, ")" matches "(" pop.\nStack is empty -> return True.',
    interaction: 'type_answer',
    typePrompt: 'Type True or False',
    acceptableAnswers: ['True', 'true', 'TRUE'],
  },
  {
    id: 'qr-code-12',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'def solve(nums, queries):\n    prefix = [0] * (len(nums) + 1)\n    for i in range(len(nums)):\n        prefix[i + 1] = prefix[i] + nums[i]\n    result = []\n    for l, r in queries:\n        result.append(prefix[r + 1] - prefix[l])\n    return result',
    answer: 'Prefix Sum / Cumulative Sum -- Builds a prefix sum array where prefix[i] = sum of nums[0..i-1]. Any subarray sum nums[l..r] can be answered in O(1) as prefix[r+1] - prefix[l].\n\nBuild: O(n), Each query: O(1)',
    interaction: 'mcq',
    choices: ['Sliding Window', 'Prefix Sum / Cumulative Sum', 'Segment Tree', 'Difference Array'],
    correctChoice: 1,
  },
  {
    id: 'qr-code-13',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums1 = [1, 2, 3, 0, 0, 0], m = 3, nums2 = [2, 5, 6], n = 3?',
    code: 'def solve(nums1, m, nums2, n):\n    p1, p2, p = m - 1, n - 1, m + n - 1\n    while p2 >= 0:\n        if p1 >= 0 and nums1[p1] > nums2[p2]:\n            nums1[p] = nums1[p1]\n            p1 -= 1\n        else:\n            nums1[p] = nums2[p2]\n            p2 -= 1\n        p -= 1\n    return nums1',
    answer: '[1, 2, 2, 3, 5, 6] -- Merges two sorted arrays in-place by filling from the back.\n\nWorking right to left avoids overwriting unprocessed elements.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (e.g. [1, 2, 3])',
    acceptableAnswers: ['[1, 2, 2, 3, 5, 6]', '[1,2,2,3,5,6]', '1, 2, 2, 3, 5, 6', '1,2,2,3,5,6'],
  },
  {
    id: 'qr-code-14',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'import heapq\n\ndef solve(graph, src):\n    dist = {src: 0}\n    heap = [(0, src)]\n    while heap:\n        d, u = heapq.heappop(heap)\n        if d > dist.get(u, float("inf")):\n            continue\n        for v, w in graph[u]:\n            nd = d + w\n            if nd < dist.get(v, float("inf")):\n                dist[v] = nd\n                heapq.heappush(heap, (nd, v))\n    return dist',
    answer: 'Dijkstra\'s Algorithm -- Finds shortest paths from a single source in a weighted graph using a min-heap. Greedily processes the closest unfinalized node and relaxes its edges.\n\nTime: O((V + E) log V)',
    interaction: 'mcq',
    choices: ['Bellman-Ford Algorithm', 'Prim\'s MST Algorithm', 'Dijkstra\'s Algorithm', 'A* Search'],
    correctChoice: 2,
  },
  {
    id: 'qr-code-15',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for s = "the sky is blue"?',
    code: 'def solve(s):\n    words = s.split()\n    left, right = 0, len(words) - 1\n    while left < right:\n        words[left], words[right] = words[right], words[left]\n        left += 1\n        right -= 1\n    return " ".join(words)',
    answer: '"blue is sky the" -- Reverses the order of words in a string.\n\nAfter split: ["the", "sky", "is", "blue"]\nSwap 0 and 3: ["blue", "sky", "is", "the"]\nSwap 1 and 2: ["blue", "is", "sky", "the"]\nJoin: "blue is sky the"',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a string)',
    acceptableAnswers: ['blue is sky the', '"blue is sky the"'],
  },
  {
    id: 'qr-code-16',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [2, 2, 1, 1, 1, 2, 2]?',
    code: 'def solve(nums):\n    candidate = None\n    count = 0\n    for n in nums:\n        if count == 0:\n            candidate = n\n        count += 1 if n == candidate else -1\n    return candidate',
    answer: '2 -- This is Boyer-Moore Majority Vote.\n\nThe candidate changes as count hits zero, but the majority element (2, appearing 4/7 times) always survives. Final candidate = 2.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['2'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADVANCED TOPICS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'qr-adv-1',
    type: 'big_o',
    title: 'Shortest Path with a Heap',
    question: 'What is the time complexity of Dijkstra\'s algorithm when implemented with a min-heap (binary heap)?',
    answer: 'O((V + E) log V). Each vertex is extracted from the heap once (V log V), and each edge relaxation may trigger a heap insert (E log V). Combined: O((V + E) log V).',
    interaction: 'mcq',
    choices: ['O(V^2)', 'O((V + E) log V)', 'O(V * E)', 'O(E log E)'],
    correctChoice: 1,
  },
  {
    id: 'qr-adv-2',
    type: 'pattern',
    title: 'Splitting a Word into Dictionary Parts',
    question: 'Given a string and a dictionary of words, determine if the string can be segmented into a sequence of one or more dictionary words. Which technique is most appropriate?',
    answer: 'Dynamic Programming (Word Break). Use a boolean DP array where dp[i] is true if the substring s[0..i] can be segmented using dictionary words. For each position, check all possible word endings.',
    interaction: 'mcq',
    choices: ['Greedy with sorting', 'Dynamic Programming', 'Sliding Window', 'Trie-only traversal'],
    correctChoice: 1,
  },
  {
    id: 'qr-adv-3',
    type: 'big_o',
    title: 'Recursive Tree Traversal Memory',
    question: 'What is the space complexity of a recursive DFS traversal on a tree with height h?',
    answer: 'O(h). The call stack grows proportionally to the depth of recursion, which equals the height of the tree. For a balanced tree h = log n, but for a skewed tree h = n.',
    interaction: 'mcq',
    choices: ['O(1)', 'O(n)', 'O(h)', 'O(n log n)'],
    correctChoice: 2,
  },
  {
    id: 'qr-adv-4',
    type: 'pattern',
    title: 'Comparing Two Sequences',
    question: 'You need to find the longest common subsequence (LCS) of two strings. Which approach is standard?',
    answer: 'DP with a 2D table. Build an (m+1) x (n+1) table where dp[i][j] stores the LCS length of the first i characters of A and first j of B. If characters match, dp[i][j] = dp[i-1][j-1] + 1; otherwise take max of dp[i-1][j] and dp[i][j-1].',
    interaction: 'mcq',
    choices: ['Two-pointer technique', 'DP with a 2D table', 'Sliding window with hash map', 'Divide and conquer'],
    correctChoice: 1,
  },
  {
    id: 'qr-adv-5',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this print?',
    code: 'def count_bits(n):\n    count = 0\n    while n:\n        count += n & 1\n        n >>= 1\n    return count\n\nprint(count_bits(13))',
    answer: '3 -- 13 in binary is 1101, which has three 1-bits. The loop checks the last bit with n & 1, then right-shifts until n becomes 0.',
    interaction: 'type_answer',
    typePrompt: 'Type the printed value',
    acceptableAnswers: ['3'],
  },
  {
    id: 'qr-adv-6',
    type: 'pattern',
    title: 'Two-Sided Graph Classification',
    question: 'You need to detect whether an undirected graph is bipartite (vertices can be divided into two groups with no edges within a group). Which technique is most appropriate?',
    answer: 'BFS/DFS with 2-coloring. Assign one color to a starting node, then alternate colors for neighbors. If you ever find a neighbor already colored with the same color as the current node, the graph is not bipartite.',
    interaction: 'mcq',
    choices: ['Topological sort', 'Union-Find with path compression', 'BFS/DFS with 2-coloring', 'Minimum spanning tree'],
    correctChoice: 2,
  },
  {
    id: 'qr-adv-7',
    type: 'big_o',
    title: 'Substring Search Efficiency',
    question: 'What is the time complexity of checking whether a pattern of length n exists within a text of length m, using KMP vs. the naive approach?',
    answer: 'O(n + m) with KMP. KMP preprocesses the pattern to build a failure function in O(n), then scans the text in O(m). The naive approach checks every starting position, giving O(n * m) worst case.',
    interaction: 'mcq',
    choices: ['O(n + m) with KMP; O(n * m) naive', 'O(n log m) with KMP; O(n * m) naive', 'O(n * m) for both', 'O(n + m) for both'],
    correctChoice: 0,
  },
  {
    id: 'qr-adv-8',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this print?',
    code: 'def find_unique(nums):\n    result = 0\n    for n in nums:\n        result ^= n\n    return result\n\nprint(find_unique([4, 1, 2, 1, 2]))',
    answer: '4 -- XOR of a number with itself is 0, and XOR with 0 is the number itself. The duplicate pairs cancel out (1^1=0, 2^2=0), leaving only 4.',
    interaction: 'type_answer',
    typePrompt: 'Type the printed value',
    acceptableAnswers: ['4'],
  },
  {
    id: 'qr-adv-9',
    type: 'pattern',
    title: 'Eviction-Based Cache Design',
    question: 'You need to implement an LRU (Least Recently Used) cache with O(1) get and put operations. Which data structure combination is standard?',
    answer: 'Hash Map + Doubly Linked List. The hash map provides O(1) key lookup, while the doubly linked list maintains access order so the least recently used item can be evicted from the tail in O(1). On access, a node is moved to the head in O(1).',
    interaction: 'mcq',
    choices: ['Min-heap + hash set', 'Hash Map + Doubly Linked List', 'Balanced BST + queue', 'Array + hash map'],
    correctChoice: 1,
  },
  {
    id: 'qr-adv-10',
    type: 'big_o',
    title: 'Growing Array Cost Per Insert',
    question: 'What is the amortized time complexity of appending to a dynamic array that doubles in capacity when full?',
    answer: 'O(1) amortized. Most appends are O(1). Occasionally the array must be copied to a new buffer of double size, costing O(n). But after n inserts only log n resizes occur, so the total cost over n appends is O(n), giving O(1) amortized per append.',
    interaction: 'mcq',
    choices: ['O(n)', 'O(log n)', 'O(1) amortized', 'O(n log n) amortized'],
    correctChoice: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEW QUESTIONS — BATCH 1: Big-O & Complexity
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'qr-bigo-30',
    type: 'big_o',
    title: 'Counting Sort',
    question: 'What is the time complexity of counting sort for n integers in the range [0, k]?',
    answer: 'O(n + k). Counting sort creates a count array of size k+1, tallies each element in O(n), then iterates the count array in O(k) to produce sorted output. It beats comparison sorts when k is O(n).',
    interaction: 'mcq',
    choices: ['O(n log n)', 'O(n + k)', 'O(n * k)', 'O(k log k)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-31',
    type: 'big_o',
    title: 'Hash Map Resize Cost',
    question: 'When a hash map with n entries triggers a resize (doubling its bucket array), what is the cost of that single resize operation?',
    answer: 'O(n). Every existing entry must be rehashed and placed into the new, larger bucket array. However, resizes happen rarely enough that the amortized cost per insertion remains O(1).',
    interaction: 'mcq',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-32',
    type: 'big_o',
    title: 'Generating All Subsets',
    question: 'How many subsets does a set of n elements have, and what is the time complexity of generating all of them?',
    answer: 'O(2^n * n). There are 2^n subsets (each element is either included or excluded). Generating each subset takes O(n) to copy, so the total is O(n * 2^n).',
    interaction: 'mcq',
    choices: ['O(n!)', 'O(n * 2^n)', 'O(2^n)', 'O(n^2)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-33',
    type: 'big_o',
    title: 'Generating All Permutations',
    question: 'What is the time complexity of generating all permutations of n distinct elements?',
    answer: 'O(n * n!). There are n! permutations, and copying each one into the result takes O(n) time. The recursive backtracking itself does O(n!) work in swaps.',
    interaction: 'mcq',
    choices: ['O(2^n)', 'O(n^n)', 'O(n * n!)', 'O(n^2)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-34',
    type: 'big_o',
    title: 'Matrix Multiplication',
    question: 'What is the time complexity of multiplying two n x n matrices using the standard algorithm?',
    answer: 'O(n^3). For each of the n^2 entries in the result matrix, you compute a dot product of a row and a column, which takes O(n). Total: n^2 * n = n^3.',
    interaction: 'mcq',
    choices: ['O(n^2)', 'O(n^2 log n)', 'O(n^3)', 'O(n^4)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-35',
    type: 'big_o',
    title: 'Radix Sort',
    question: 'What is the time complexity of radix sort for n integers, each with at most d digits, where each digit has k possible values?',
    answer: 'O(d * (n + k)). Radix sort runs counting sort once per digit position. Each pass is O(n + k). With d passes, the total is O(d * (n + k)). For fixed-width integers (constant d and k), this simplifies to O(n).',
    interaction: 'mcq',
    choices: ['O(n log n)', 'O(d * n * k)', 'O(d * (n + k))', 'O(n * k)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-36',
    type: 'big_o',
    title: 'Adjacency Matrix Space',
    question: 'What is the space complexity of storing a graph with V vertices and E edges as an adjacency matrix?',
    answer: 'O(V^2). An adjacency matrix allocates a V x V grid regardless of how many edges exist. For sparse graphs (E << V^2), this wastes significant space compared to an adjacency list at O(V + E).',
    interaction: 'mcq',
    choices: ['O(V + E)', 'O(V^2)', 'O(E)', 'O(V * E)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-37',
    type: 'big_o',
    title: 'Removing Duplicates from Sorted Array',
    question: 'What is the time complexity of removing duplicates in-place from a sorted array of n elements?',
    answer: 'O(n). Use a slow pointer for the write position and a fast pointer to scan. Because the array is sorted, duplicates are adjacent. One pass with two pointers does it in O(n) time and O(1) space.',
    interaction: 'mcq',
    choices: ['O(n log n)', 'O(n)', 'O(n^2)', 'O(log n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-38',
    type: 'big_o',
    title: 'Bellman-Ford Algorithm',
    question: 'What is the time complexity of the Bellman-Ford algorithm for finding shortest paths from a single source in a graph with V vertices and E edges?',
    answer: 'O(V * E). Bellman-Ford relaxes all E edges V-1 times. Unlike Dijkstra, it handles negative edge weights. If any edge can still be relaxed after V-1 passes, a negative cycle exists.',
    interaction: 'mcq',
    choices: ['O(V + E)', 'O((V + E) log V)', 'O(V * E)', 'O(V^2 * E)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-39',
    type: 'big_o',
    title: 'Trie Prefix Search',
    question: 'What is the time complexity of finding all words in a trie that share a common prefix of length P, if there are W matching words with average length L?',
    answer: 'O(P + W * L). Traversing to the prefix node takes O(P). Then a DFS from that node visits all matching words, which takes O(W * L) in total to enumerate them.',
    interaction: 'mcq',
    choices: ['O(P)', 'O(P + W * L)', 'O(n * L)', 'O(P * W)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-40',
    type: 'big_o',
    title: 'Selection Algorithm',
    question: 'What is the average time complexity of Quickselect for finding the kth smallest element in an unsorted array?',
    answer: 'O(n) average. Like quicksort, it partitions around a pivot, but only recurses into ONE side (the side containing position k). On average, work halves each iteration: n + n/2 + n/4 + ... = O(2n) = O(n). Worst case is O(n^2).',
    interaction: 'mcq',
    choices: ['O(n log n)', 'O(n)', 'O(n log k)', 'O(k * n)'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-41',
    type: 'big_o',
    title: 'String Concatenation in a Loop',
    question: 'In Python, what is the time complexity of building a string by concatenating one character at a time in a loop of n iterations using s += char?',
    answer: 'O(n^2) in the worst case. Strings are immutable, so each += creates a new string object and copies the existing content. The copy on iteration i costs O(i), and 1+2+...+n = O(n^2). Use "".join(list) instead for O(n).',
    interaction: 'mcq',
    choices: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(2^n)'],
    correctChoice: 2,
  },
  {
    id: 'qr-bigo-42',
    type: 'big_o',
    title: 'Checking if a Number is Prime',
    question: 'What is the time complexity of the basic trial division algorithm for checking if n is prime?',
    answer: 'O(sqrt(n)). You only need to check divisors up to sqrt(n). If n has a factor larger than sqrt(n), it must also have one smaller than sqrt(n). So testing 2 through sqrt(n) is sufficient.',
    interaction: 'mcq',
    choices: ['O(n)', 'O(n / 2)', 'O(sqrt(n))', 'O(log n)'],
    correctChoice: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEW QUESTIONS — BATCH 2: Pattern Recognition
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'qr-pattern-30',
    type: 'pattern',
    title: 'Maximum Subarray Sum',
    question: 'Given an array of integers (positive and negative), find the contiguous subarray with the largest sum. Which technique solves this in O(n)?',
    answer: 'Kadane\'s Algorithm. Track the maximum sum ending at each position: currentMax = max(num, currentMax + num). If adding the current number makes the sum negative, start a new subarray. Track the global maximum across all positions.',
    interaction: 'mcq',
    choices: ['Prefix Sum with Binary Search', 'Kadane\'s Algorithm', 'Sliding Window with fixed size', 'Divide and Conquer only'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-31',
    type: 'pattern',
    title: 'Range Update on an Array',
    question: 'You need to add a value v to every element in the range [l, r] across many such operations, then read the final array. Which technique avoids O(n) work per update?',
    answer: 'Difference Array. Create a diff array where diff[l] += v and diff[r+1] -= v for each update. After all updates, compute the prefix sum of diff to get the final array. Each update is O(1), and the final computation is O(n).',
    interaction: 'mcq',
    choices: ['Segment Tree', 'Difference Array', 'Binary Indexed Tree', 'Prefix Sum Array'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-32',
    type: 'pattern',
    title: 'Finding a Duplicate in [1..n]',
    question: 'An array of n+1 integers contains values in [1, n], with exactly one duplicate. You cannot modify the array and must use O(1) space. Which technique finds the duplicate?',
    answer: 'Floyd\'s Cycle Detection (fast & slow pointers). Treat the array as a linked list where index i points to nums[i]. The duplicate creates a cycle. Use fast/slow pointers to find the cycle entry point, which is the duplicate value.',
    interaction: 'mcq',
    choices: ['Sorting the array', 'XOR of all elements', 'Floyd\'s Cycle Detection', 'Binary search on value range'],
    correctChoice: 2,
  },
  {
    id: 'qr-pattern-33',
    type: 'pattern',
    title: 'Efficient Range Minimum Queries',
    question: 'After preprocessing, you need to answer many "what is the minimum value in range [l, r]?" queries, each in O(1) time. Which technique achieves this?',
    answer: 'Sparse Table. Precompute minimums for all power-of-2 length ranges in O(n log n). Each query overlaps two precomputed ranges whose union covers [l, r], and the minimum of overlapping ranges is still the correct minimum. O(1) per query.',
    interaction: 'mcq',
    choices: ['Segment Tree', 'Sparse Table', 'Prefix Sum Array', 'Monotonic Stack'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-34',
    type: 'pattern',
    title: 'Longest Increasing Subsequence',
    question: 'You need to find the length of the longest strictly increasing subsequence of an array. What is the optimal time complexity and which technique achieves it?',
    answer: 'O(n log n) using Patience Sorting (binary search + tails array). Maintain an array of the smallest tail element for each subsequence length. For each number, use binary search to find where it extends or replaces a tail. The length of the tails array is the LIS length.',
    interaction: 'mcq',
    choices: ['O(n^2) DP is the best possible', 'O(n log n) using binary search with a tails array', 'O(n) with a greedy scan', 'O(n log n) using a segment tree'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-35',
    type: 'pattern',
    title: 'Rotated Sorted Array Search',
    question: 'A sorted array has been rotated at some unknown pivot (e.g., [4,5,6,7,0,1,2]). You need to search for a target value in O(log n) time. Which technique should you use?',
    answer: 'Modified Binary Search. At each step, one half of the array is guaranteed to be sorted. Determine which half is sorted, then check if the target falls within that sorted half. If so, search there; otherwise, search the other half.',
    interaction: 'mcq',
    choices: ['Linear scan -- rotation breaks binary search', 'Modified Binary Search', 'Find the pivot first, then standard binary search', 'Two-pointer from both ends'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-36',
    type: 'pattern',
    title: 'Shortest Transformation Sequence',
    question: 'Given a start word, an end word, and a dictionary, find the shortest transformation sequence where you change one letter at a time and each intermediate word must be in the dictionary. Which technique should you use?',
    answer: 'BFS. Model each word as a graph node with edges to words that differ by one letter. BFS from the start word guarantees finding the shortest path (fewest transformations) to the end word.',
    interaction: 'mcq',
    choices: ['DFS with memoization', 'BFS', 'Dynamic Programming', 'Greedy (change the letter closest to target)'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-37',
    type: 'pattern',
    title: '0/1 Knapsack',
    question: 'You have items with weights and values, and a knapsack with a weight capacity W. Each item can be taken at most once. How do you maximize total value?',
    answer: 'Dynamic Programming (2D or 1D rolling array). Build a table dp[i][w] = max value using the first i items with capacity w. For each item, decide whether to include it or skip it. Greedy by value/weight ratio does NOT guarantee optimality for 0/1 knapsack.',
    interaction: 'mcq',
    choices: ['Greedy by value-to-weight ratio', 'Dynamic Programming', 'Backtracking without pruning', 'Sorting by weight then filling'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-38',
    type: 'pattern',
    title: 'Level-by-Level Tree Processing',
    question: 'You need to process a binary tree one level at a time (e.g., find the average value at each depth). Which traversal gives you nodes grouped by level?',
    answer: 'BFS with level tracking. Use a queue and process nodes level by level. At each level, record the queue size, then dequeue exactly that many nodes (all from the current level) while enqueuing their children for the next level.',
    interaction: 'mcq',
    choices: ['In-order DFS', 'BFS with level tracking', 'Post-order DFS', 'Pre-order DFS with depth counter'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-39',
    type: 'pattern',
    title: 'Minimum Spanning Tree',
    question: 'You need to connect all nodes in a weighted undirected graph with the minimum total edge weight. Which algorithm uses a priority queue to greedily add the cheapest edge from the growing tree?',
    answer: 'Prim\'s Algorithm. Start from any node, repeatedly add the cheapest edge connecting a visited node to an unvisited node. Uses a min-heap for efficient edge selection. Time: O(E log V). Kruskal\'s sorts all edges and uses Union-Find instead.',
    interaction: 'mcq',
    choices: ['Kruskal\'s Algorithm', 'Prim\'s Algorithm', 'Dijkstra\'s Algorithm', 'Bellman-Ford Algorithm'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-40',
    type: 'pattern',
    title: 'Detecting a Negative Cycle',
    question: 'You need to determine if a weighted directed graph contains a negative-weight cycle reachable from a source. Which algorithm can detect this?',
    answer: 'Bellman-Ford. After V-1 relaxation passes, run one more pass. If any edge can still be relaxed, a negative cycle exists. Dijkstra cannot handle negative edges at all, so it cannot detect negative cycles.',
    interaction: 'mcq',
    choices: ['Dijkstra\'s Algorithm', 'Floyd-Warshall only', 'Bellman-Ford', 'Topological Sort'],
    correctChoice: 2,
  },
  {
    id: 'qr-pattern-41',
    type: 'pattern',
    title: 'Partitioning Equal Subset Sum',
    question: 'Given an array of positive integers, determine if you can partition it into two subsets with equal sum. Which technique should you use?',
    answer: 'Dynamic Programming (subset sum variant). The target is totalSum / 2. Use a boolean DP array dp[s] = "can we reach sum s using some subset of elements?" For each element, update the DP array from right to left to avoid using an element twice.',
    interaction: 'mcq',
    choices: ['Greedy -- always add to the smaller subset', 'Two Pointers after sorting', 'Dynamic Programming (subset sum)', 'Backtracking is the only option'],
    correctChoice: 2,
  },
  {
    id: 'qr-pattern-42',
    type: 'pattern',
    title: 'All Shortest Paths Between All Pairs',
    question: 'You need the shortest path between every pair of vertices in a graph with V vertices. Which algorithm computes all-pairs shortest paths?',
    answer: 'Floyd-Warshall. It uses a 3-nested-loop DP approach: for each intermediate vertex k, update dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]). Time: O(V^3). Handles negative edges but not negative cycles.',
    interaction: 'mcq',
    choices: ['Run BFS from each vertex', 'Floyd-Warshall', 'Run Dijkstra from each vertex', 'Bellman-Ford with matrix exponentiation'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-43',
    type: 'pattern',
    title: 'String Matching with Wildcards',
    question: 'Given a string and a pattern with "?" (matches any single character) and "*" (matches any sequence including empty), determine if the string matches the pattern. Which technique works?',
    answer: 'Dynamic Programming. Build a 2D table dp[i][j] = "does pattern[0..i] match string[0..j]?". For "*", either skip it (dp[i-1][j]) or use it to match one more character (dp[i][j-1]). Greedy fails because "*" can match variable lengths.',
    interaction: 'mcq',
    choices: ['Regular expression engine only', 'Dynamic Programming', 'Greedy left-to-right scan', 'Trie-based matching'],
    correctChoice: 1,
  },
  {
    id: 'qr-pattern-44',
    type: 'pattern',
    title: 'Stock Trading with One Transaction',
    question: 'Given daily stock prices, find the maximum profit from buying once and selling once (buy before sell). Which approach solves this in O(n) time?',
    answer: 'Track the minimum price seen so far and the maximum profit at each step. At each day, profit = price - minSoFar. Update minSoFar and maxProfit as you scan left to right. One pass, O(1) space.',
    interaction: 'mcq',
    choices: ['Sort prices and take the difference of max and min', 'Track minimum price so far and update max profit at each step', 'Use a stack to find price peaks and valleys', 'Dynamic programming with 2D state table'],
    correctChoice: 1,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEW QUESTIONS — BATCH 3: Code Reading & Tracing
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'qr-code-20',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [0, 1, 0, 3, 12]?',
    code: 'def solve(nums):\n    write = 0\n    for read in range(len(nums)):\n        if nums[read] != 0:\n            nums[write], nums[read] = nums[read], nums[write]\n            write += 1\n    return nums',
    answer: '[1, 3, 12, 0, 0] -- This moves all zeros to the end while preserving the relative order of non-zero elements.\n\nwrite tracks the next position for a non-zero value. Each non-zero element is swapped to the write position, pushing zeros rightward.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (e.g. [1, 2, 3])',
    acceptableAnswers: ['[1, 3, 12, 0, 0]', '[1,3,12,0,0]', '1, 3, 12, 0, 0', '1,3,12,0,0'],
  },
  {
    id: 'qr-code-21',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [1, 1, 2, 2, 2, 3]?',
    code: 'def solve(nums):\n    if not nums:\n        return 0\n    w = 1\n    for r in range(1, len(nums)):\n        if nums[r] != nums[r - 1]:\n            nums[w] = nums[r]\n            w += 1\n    return w',
    answer: '3 -- This removes duplicates in-place from a sorted array and returns the count of unique elements.\n\nUnique elements: 1, 2, 3. The array becomes [1, 2, 3, ...] and w = 3.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['3'],
  },
  {
    id: 'qr-code-22',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for matrix = [[1,2,3],[4,5,6],[7,8,9]] and target = 5?',
    code: 'def solve(matrix, target):\n    rows, cols = len(matrix), len(matrix[0])\n    r, c = 0, cols - 1\n    while r < rows and c >= 0:\n        if matrix[r][c] == target:\n            return True\n        elif matrix[r][c] < target:\n            r += 1\n        else:\n            c -= 1\n    return False',
    answer: 'True -- This searches a row-sorted and column-sorted 2D matrix starting from the top-right corner.\n\nStart at (0,2)=3 < 5, move down. (1,2)=6 > 5, move left. (1,1)=5 == target, return True.\n\nTime: O(m + n).',
    interaction: 'type_answer',
    typePrompt: 'Type True or False',
    acceptableAnswers: ['True', 'true', 'TRUE'],
  },
  {
    id: 'qr-code-23',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'def solve(nums):\n    cur_max = global_max = nums[0]\n    for n in nums[1:]:\n        cur_max = max(n, cur_max + n)\n        global_max = max(global_max, cur_max)\n    return global_max',
    answer: 'Kadane\'s Algorithm -- Finds the maximum sum contiguous subarray. At each element, decide whether to extend the current subarray or start fresh. Track the global maximum across all positions.\n\nTime: O(n), Space: O(1)',
    interaction: 'mcq',
    choices: ['Prefix Sum', 'Kadane\'s Algorithm', 'Sliding Window', 'Divide and Conquer'],
    correctChoice: 1,
  },
  {
    id: 'qr-code-24',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for prices = [7, 1, 5, 3, 6, 4]?',
    code: 'def solve(prices):\n    min_price = float("inf")\n    max_profit = 0\n    for p in prices:\n        min_price = min(min_price, p)\n        max_profit = max(max_profit, p - min_price)\n    return max_profit',
    answer: '5 -- Buy at price 1 (day 1), sell at price 6 (day 4), profit = 5.\n\nThe algorithm tracks the lowest price seen and computes the best profit at each step:\nDay 0: min=7, profit=0\nDay 1: min=1, profit=0\nDay 2: min=1, profit=4\nDay 3: min=1, profit=2\nDay 4: min=1, profit=5\nDay 5: min=1, profit=3',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['5'],
  },
  {
    id: 'qr-code-25',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for s = "anagram" and t = "nagaram"?',
    code: 'def solve(s, t):\n    if len(s) != len(t):\n        return False\n    counts = {}\n    for c in s:\n        counts[c] = counts.get(c, 0) + 1\n    for c in t:\n        counts[c] = counts.get(c, 0) - 1\n        if counts[c] < 0:\n            return False\n    return True',
    answer: 'True -- This checks if two strings are anagrams by comparing character frequencies.\n\nBuild a frequency map from s, then decrement for each character in t. If any count goes negative, t has a character that s doesn\'t (or has more of it). Both strings have the same characters in the same quantities.',
    interaction: 'type_answer',
    typePrompt: 'Type True or False',
    acceptableAnswers: ['True', 'true', 'TRUE'],
  },
  {
    id: 'qr-code-26',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'def solve(root):\n    if not root:\n        return 0\n    left = solve(root.left)\n    right = solve(root.right)\n    if left == -1 or right == -1:\n        return -1\n    if abs(left - right) > 1:\n        return -1\n    return max(left, right) + 1',
    answer: 'Bottom-up check for a balanced binary tree. Returns the height if balanced, or -1 if any subtree is unbalanced (height difference > 1). This avoids the O(n^2) cost of checking height at every node separately.\n\nTime: O(n), one pass.',
    interaction: 'mcq',
    choices: ['Tree height calculation', 'Balanced tree check (bottom-up)', 'BST validation', 'Diameter of binary tree'],
    correctChoice: 1,
  },
  {
    id: 'qr-code-27',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [1, 2, 3, 4] and target = 2?',
    code: 'def solve(nums, target):\n    lo, hi = 0, len(nums)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if nums[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo',
    answer: '1 -- This is bisect_left (lower bound binary search). It finds the leftmost position where target could be inserted to keep the array sorted.\n\nStep 1: lo=0, hi=4, mid=2, nums[2]=3 >= 2, hi=2\nStep 2: lo=0, hi=2, mid=1, nums[1]=2 >= 2, hi=1\nStep 3: lo=0, hi=1, mid=0, nums[0]=1 < 2, lo=1\nlo=hi=1, return 1.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['1'],
  },
  {
    id: 'qr-code-28',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [100, 4, 200, 1, 3, 2]?',
    code: 'def solve(nums):\n    s = set(nums)\n    best = 0\n    for n in s:\n        if n - 1 not in s:\n            length = 1\n            while n + length in s:\n                length += 1\n            best = max(best, length)\n    return best',
    answer: '4 -- This finds the longest consecutive sequence.\n\nThe key optimization: only start counting from numbers that are the START of a sequence (n-1 not in set). Starting from 1: 1,2,3,4 are all in the set, so length = 4. Starting from 100: only 100, length = 1. Starting from 200: only 200, length = 1.\n\nTime: O(n).',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['4'],
  },
  {
    id: 'qr-code-29',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'def solve(nums):\n    stack = []\n    result = [-1] * len(nums)\n    for i in range(len(nums)):\n        while stack and nums[i] > nums[stack[-1]]:\n            result[stack.pop()] = nums[i]\n        stack.append(i)\n    return result',
    answer: 'Monotonic Stack -- Next Greater Element. The stack holds indices in decreasing order of their values. When a larger value is found, all smaller values on the stack get their "next greater element" answer. Elements with no greater element to the right keep -1.\n\nTime: O(n) -- each index is pushed and popped at most once.',
    interaction: 'mcq',
    choices: ['Stack-based expression evaluation', 'Monotonic Stack (Next Greater Element)', 'Stack-based sorting', 'Histogram area calculation'],
    correctChoice: 1,
  },
  {
    id: 'qr-code-30',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for root = [3, 9, 20, null, null, 15, 7] (a binary tree)?',
    code: 'from collections import deque\n\ndef solve(root):\n    if not root:\n        return 0\n    q = deque([root])\n    depth = 0\n    while q:\n        depth += 1\n        for _ in range(len(q)):\n            node = q.popleft()\n            if node.left:\n                q.append(node.left)\n            if node.right:\n                q.append(node.right)\n    return depth',
    answer: '3 -- This computes the maximum depth (height) of a binary tree using BFS level-order traversal.\n\nLevel 1: [3] (depth=1)\nLevel 2: [9, 20] (depth=2)\nLevel 3: [15, 7] (depth=3)\nNo more levels, return 3.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['3'],
  },
  {
    id: 'qr-code-31',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for s = "aab"?',
    code: 'def solve(s):\n    result = []\n    def backtrack(start, path):\n        if start == len(s):\n            result.append(path[:])\n            return\n        for end in range(start + 1, len(s) + 1):\n            sub = s[start:end]\n            if sub == sub[::-1]:\n                path.append(sub)\n                backtrack(end, path)\n                path.pop()\n    backtrack(0, [])\n    return result',
    answer: '[["a","a","b"],["aa","b"]] -- This generates all palindrome partitionings of the string.\n\nFrom index 0: "a" is a palindrome -> recurse on "ab"\n  From index 1: "a" is a palindrome -> recurse on "b"\n    "b" is a palindrome -> partition ["a","a","b"]\n  "ab" is not a palindrome -> skip\n"aa" is a palindrome -> recurse on "b"\n  "b" is a palindrome -> partition ["aa","b"]\n"aab" is not a palindrome -> skip',
    interaction: 'mcq',
    choices: [
      '[["a","a","b"],["aa","b"]]',
      '[["a","ab"],["aa","b"]]',
      '[["aab"]]',
      '[["a","a","b"],["aa","b"],["aab"]]',
    ],
    correctChoice: 0,
  },
  {
    id: 'qr-code-32',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for n = 3 and edges = [[0,1],[1,2],[2,0]]?',
    code: 'def solve(n, edges):\n    parent = list(range(n))\n    def find(x):\n        while parent[x] != x:\n            parent[x] = parent[parent[x]]\n            x = parent[x]\n        return x\n    for u, v in edges:\n        ru, rv = find(u), find(v)\n        if ru == rv:\n            return [u, v]\n        parent[rv] = ru\n    return []',
    answer: '[2, 0] -- This finds the redundant edge that creates a cycle using Union-Find.\n\nEdge [0,1]: merge 0 and 1. parent = [0,0,2]\nEdge [1,2]: merge 0 and 2. parent = [0,0,0]\nEdge [2,0]: find(2)=0, find(0)=0, same root -> cycle detected, return [2,0].',
    interaction: 'mcq',
    choices: ['[0, 1]', '[1, 2]', '[2, 0]', '[]'],
    correctChoice: 2,
  },
  {
    id: 'qr-code-33',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [2, 3, 1, 1, 4]?',
    code: 'def solve(nums):\n    reach = 0\n    for i in range(len(nums)):\n        if i > reach:\n            return False\n        reach = max(reach, i + nums[i])\n    return True',
    answer: 'True -- This is the Jump Game greedy approach.\n\nTrack the farthest index reachable. At each index, if you can\'t reach it, return False. Otherwise update the maximum reach.\n\ni=0: reach = max(0, 0+2) = 2\ni=1: reach = max(2, 1+3) = 4\ni=2: reach = max(4, 2+1) = 4\ni=3: reach = max(4, 3+1) = 4\ni=4: reach = max(4, 4+4) = 8\nReached the end, return True.',
    interaction: 'type_answer',
    typePrompt: 'Type True or False',
    acceptableAnswers: ['True', 'true', 'TRUE'],
  },
  {
    id: 'qr-code-34',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [1, 2, 4, 5, 6] and target = 3?',
    code: 'def solve(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return lo',
    answer: '2 -- Standard binary search that returns the insertion point when the target is not found.\n\nStep 1: lo=0, hi=4, mid=2, nums[2]=4 > 3, hi=1\nStep 2: lo=0, hi=1, mid=0, nums[0]=1 < 3, lo=1\nStep 3: lo=1, hi=1, mid=1, nums[1]=2 < 3, lo=2\nlo > hi, return lo=2 (insertion point).',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['2'],
  },
  {
    id: 'qr-code-35',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for intervals = [[1,3],[2,6],[8,10],[15,18]]?',
    code: 'def solve(intervals):\n    intervals.sort(key=lambda x: x[0])\n    merged = [intervals[0]]\n    for start, end in intervals[1:]:\n        if start <= merged[-1][1]:\n            merged[-1][1] = max(merged[-1][1], end)\n        else:\n            merged.append([start, end])\n    return merged',
    answer: '[[1,6],[8,10],[15,18]] -- This merges overlapping intervals.\n\nSort by start time (already sorted). [1,3] starts merged list.\n[2,6]: 2 <= 3, overlap -> merge to [1,6].\n[8,10]: 8 > 6, no overlap -> add [8,10].\n[15,18]: 15 > 10, no overlap -> add [15,18].',
    interaction: 'mcq',
    choices: [
      '[[1,6],[8,10],[15,18]]',
      '[[1,3],[2,6],[8,10],[15,18]]',
      '[[1,6],[8,18]]',
      '[[1,18]]',
    ],
    correctChoice: 0,
  },
  {
    id: 'qr-code-36',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for matrix = [[1,2,3],[4,5,6],[7,8,9]]?',
    code: 'def solve(matrix):\n    n = len(matrix)\n    for i in range(n):\n        for j in range(i + 1, n):\n            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n    for row in matrix:\n        row.reverse()\n    return matrix',
    answer: '[[7,4,1],[8,5,2],[9,6,3]] -- This rotates a matrix 90 degrees clockwise.\n\nStep 1: Transpose (swap across diagonal):\n[[1,4,7],[2,5,8],[3,6,9]]\nStep 2: Reverse each row:\n[[7,4,1],[8,5,2],[9,6,3]]',
    interaction: 'mcq',
    choices: [
      '[[3,6,9],[2,5,8],[1,4,7]]',
      '[[7,4,1],[8,5,2],[9,6,3]]',
      '[[9,8,7],[6,5,4],[3,2,1]]',
      '[[1,4,7],[2,5,8],[3,6,9]]',
    ],
    correctChoice: 1,
  },
  {
    id: 'qr-code-37',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [1, 5, 11, 5]?',
    code: 'def solve(nums):\n    total = sum(nums)\n    if total % 2 != 0:\n        return False\n    target = total // 2\n    dp = [False] * (target + 1)\n    dp[0] = True\n    for n in nums:\n        for s in range(target, n - 1, -1):\n            dp[s] = dp[s] or dp[s - n]\n    return dp[target]',
    answer: 'True -- This checks if the array can be partitioned into two subsets with equal sum.\n\ntotal = 22, target = 11. Using DP subset sum: can we pick elements summing to 11?\nYes: {1, 5, 5} = 11. The other subset {11} = 11.\nSo dp[11] = True.',
    interaction: 'type_answer',
    typePrompt: 'Type True or False',
    acceptableAnswers: ['True', 'true', 'TRUE'],
  },
  {
    id: 'qr-code-38',
    type: 'code_reading',
    title: 'Name That Pattern',
    question: 'What algorithmic pattern does this code implement?',
    code: 'def solve(s, p):\n    m, n = len(s), len(p)\n    dp = [[False] * (n + 1) for _ in range(m + 1)]\n    dp[0][0] = True\n    for j in range(1, n + 1):\n        if p[j - 1] == "*":\n            dp[0][j] = dp[0][j - 2]\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if p[j - 1] == "." or p[j - 1] == s[i - 1]:\n                dp[i][j] = dp[i - 1][j - 1]\n            elif p[j - 1] == "*":\n                dp[i][j] = dp[i][j - 2]\n                if p[j - 2] == "." or p[j - 2] == s[i - 1]:\n                    dp[i][j] = dp[i][j] or dp[i - 1][j]\n    return dp[m][n]',
    answer: 'Regular Expression Matching with DP. The pattern supports "." (any character) and "*" (zero or more of the preceding character). The 2D DP table dp[i][j] tracks whether the first i characters of s match the first j characters of p.\n\nTime: O(m * n), Space: O(m * n)',
    interaction: 'mcq',
    choices: ['Wildcard Pattern Matching', 'Regular Expression Matching (DP)', 'Edit Distance', 'Longest Common Subsequence'],
    correctChoice: 1,
  },
  {
    id: 'qr-bigo-43',
    type: 'big_o',
    title: 'Sieve of Eratosthenes',
    question: 'What is the time complexity of the Sieve of Eratosthenes for finding all primes up to n?',
    answer: 'O(n log log n). The sieve iterates through each prime p and marks its multiples. The sum of n/p for all primes p up to n converges to n * log(log n) by the prime harmonic series. This is nearly linear in practice.',
    interaction: 'mcq',
    choices: ['O(n)', 'O(n log n)', 'O(n log log n)', 'O(n * sqrt(n))'],
    correctChoice: 2,
  },
  {
    id: 'qr-pattern-45',
    type: 'pattern',
    title: 'Minimum Window Containing All Characters',
    question: 'Given strings s and t, find the shortest substring of s that contains every character in t (including duplicates). Which technique should you use?',
    answer: 'Sliding Window with two frequency maps. Expand the right pointer to include characters, and contract the left pointer to minimize the window once all characters are covered. Track how many required characters are satisfied to know when the window is valid. O(n) time.',
    interaction: 'mcq',
    choices: ['Two Pointers (converging)', 'Sorting both strings', 'Sliding Window with frequency tracking', 'Dynamic Programming'],
    correctChoice: 2,
  },
  {
    id: 'qr-code-39',
    type: 'code_reading',
    title: 'Trace the Output',
    question: 'What does this return for nums = [3, 0, 1]?',
    code: 'def solve(nums):\n    n = len(nums)\n    expected = n * (n + 1) // 2\n    return expected - sum(nums)',
    answer: '2 -- This finds the missing number from the range [0, n] using the sum formula.\n\nn = 3, so the expected sum of [0,1,2,3] = 3*4/2 = 6.\nActual sum = 3+0+1 = 4.\nMissing = 6 - 4 = 2.',
    interaction: 'type_answer',
    typePrompt: 'Type the return value (a number)',
    acceptableAnswers: ['2'],
  },
];
